env: dev # dev、test、prod、local

server:
  name: moon监控系统-demo服务
  metadata:
    description: 一款始于prometheus，不止于prometheus的一站式监控系统， 专为简化云原生监控的运维工作而设计， 旨在帮助企业快速部署云原生监控系统， 降低运维成本， 提升运维效率。
  http:
    addr: 0.0.0.0:5000
    timeout: 2s
  grpc:
    addr: 0.0.0.0:6000
    timeout: 2s
  jwt:
    sign_key: "moon-sign_key"
    issuer: "moon监控系统"
    white_list:
      - /api.admin.authorization.Authorization/Login
      - /api.admin.authorization.Authorization/Captcha
      - /api.admin.authorization.Authorization/CreatePassword
    rbac_white_list:
      - /api.admin.authorization.Authorization/Login
      - /api.admin.authorization.Authorization/Captcha
      - /api.admin.authorization.Authorization/CreatePassword

data:
  database:
    driver: "mysql"
    dsn: "root:b4fG8tM#@tcp(121.41.168.20:3306)/moon?charset=utf8mb4&parseTime=True&loc=Local"
  bizDatabase:
    driver: "mysql"
    dsn: "root:b4fG8tM#@tcp(121.41.168.20:3306)/moon?charset=utf8mb4&parseTime=True&loc=Local"
  cache:
    redis:
      network: "tcp"
      addr: 121.41.168.20:6381
      db: 1
      password: ""
      read_timeout: 0.2s
      write_timeout: 0.2s
      dial_timeout: 0.2s
    nutsDB:
      path: ./tmp/nutsdb
      bucket: test
mq:
  kafka:
    Endpoints:
      - 192.168.100.9:9092
    clientID: moon-client
